# Generated by Django 4.2.7 on 2026-02-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='food_advised',
            field=models.JSONField(blank=True, default=list, help_text='List of foods recommended when taking this medicine'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='food_to_avoid',
            field=models.JSONField(blank=True, default=list, help_text='List of foods to avoid when taking this medicine'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='instructions',
            field=models.TextField(blank=True, help_text='Special instructions for taking medicine', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dose_per_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
