# Generated by Django 6.0.1 on 2026-02-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicine_food_advised_medicine_food_to_avoid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='scientific_name',
            field=models.CharField(blank=True, help_text='Scientific/Generic name - never translate', max_length=200, null=True),
        ),
    ]
