# Generated by Django 6.0.1 on 2026-02-14 10:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_medicine_scientific_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Commercial name of the drug', max_length=200)),
                ('generic_name', models.CharField(help_text='Generic/active ingredient name', max_length=200)),
                ('atc_code', models.CharField(blank=True, help_text='Anatomical Therapeutic Chemical classification code', max_length=10, null=True)),
                ('is_registered_in_rwanda', models.BooleanField(default=False, help_text='Whether this drug is registered by Rwanda FDA')),
                ('is_essential_in_rwanda', models.BooleanField(default=False, help_text='Whether this drug is on Rwanda Essential Medicines List')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text='Patient age in years', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('is_pregnant', models.BooleanField(default=False, help_text='Whether the patient is pregnant')),
                ('is_lactating', models.BooleanField(default=False, help_text='Whether the patient is lactating/breastfeeding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
            },
        ),
        migrations.CreateModel(
            name='Contraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.CharField(choices=[('infant_toddler', '0-5 years'), ('child', '6-11 years'), ('adult', '12-64 years'), ('elderly', '65+ years'), ('pregnant', 'Pregnant'), ('lactating', 'Lactating')], help_text='Patient population group this contraindication applies to', max_length=20)),
                ('condition', models.CharField(help_text='Specific medical condition or situation', max_length=200)),
                ('severity', models.CharField(choices=[('absolute', 'Absolute Contraindication'), ('relative', 'Relative Contraindication')], help_text='Severity level of the contraindication', max_length=10)),
                ('description', models.TextField(help_text='Detailed description of the contraindication')),
                ('source', models.CharField(help_text='Source of this contraindication information (e.g., WHO, Rwanda FDA)', max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(help_text='The drug this contraindication applies to', on_delete=django.db.models.deletion.CASCADE, related_name='contraindications', to='medicines.drug')),
            ],
            options={
                'verbose_name': 'Contraindication',
                'verbose_name_plural': 'Contraindications',
                'ordering': ['drug', 'population', 'severity'],
                'unique_together': {('drug', 'population', 'condition')},
            },
        ),
    ]
