# Generated by Django 6.0.1 on 2026-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_drug_patientprofile_contraindication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='notes',
            field=models.TextField(blank=True, help_text='Free-text notes about the medication', null=True),
        ),
    ]
