# Generated by Django 5.2.11 on 2026-02-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_medicine_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, help_text='UPC/EAN barcode number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_photo',
            field=models.ImageField(blank=True, help_text='Photo of the medicine packaging or pill', null=True, upload_to='medicine_photos/%Y/%m/'),
        ),
    ]
