# Generated by ChatGPT on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0006_medicine_barcode_medicine_medicine_photo"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(fields=["user", "is_active", "completed"], name="med_user_active_completed_idx"),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(fields=["user", "created_at"], name="med_user_created_at_idx"),
        ),
    ]

