# Generated by Django 4.2.7 on 2026-02-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_medicine_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RwandaFDADrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='Rwanda FDA registration number (e.g., RWANDA-FDA24/HM/0769/0004)', max_length=100, unique=True)),
                ('brand_name', models.CharField(help_text='Brand/Trade name of the drug', max_length=200)),
                ('generic_name', models.CharField(help_text='Generic name / active ingredient', max_length=500)),
                ('strength', models.CharField(help_text='Drug strength (e.g., 500mg, 1% w/v)', max_length=200)),
                ('dosage_form', models.CharField(help_text='Dosage form (e.g., Tablet, Capsule, Injection)', max_length=200)),
                ('manufacturer', models.CharField(help_text='Drug manufacturer', max_length=300)),
                ('country', models.CharField(help_text='Country of manufacture', max_length=100)),
                ('distributor', models.CharField(help_text='Distributor company', max_length=300)),
                ('local_agent', models.CharField(help_text='Local agent in Rwanda', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this registration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rwanda FDA Drug',
                'verbose_name_plural': 'Rwanda FDA Drugs',
                'ordering': ['brand_name', 'generic_name'],
            },
        ),
        migrations.RenameIndex(
            model_name='medicine',
            new_name='medicines_m_user_id_89f6dc_idx',
            old_name='med_user_active_completed_idx',
        ),
        migrations.RenameIndex(
            model_name='medicine',
            new_name='medicines_m_user_id_b54c74_idx',
            old_name='med_user_created_at_idx',
        ),
        migrations.AddIndex(
            model_name='rwandafdadrug',
            index=models.Index(fields=['brand_name'], name='medicines_r_brand_n_1fc655_idx'),
        ),
        migrations.AddIndex(
            model_name='rwandafdadrug',
            index=models.Index(fields=['generic_name'], name='medicines_r_generic_536658_idx'),
        ),
        migrations.AddIndex(
            model_name='rwandafdadrug',
            index=models.Index(fields=['registration_number'], name='medicines_r_registr_0c6837_idx'),
        ),
    ]
