# Generated by Django 4.2.7 on 2026-02-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_rwandafdadrug_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rwandafdadrug',
            name='medicines_r_brand_n_1fc655_idx',
        ),
        migrations.RemoveIndex(
            model_name='rwandafdadrug',
            name='medicines_r_generic_536658_idx',
        ),
        migrations.AlterField(
            model_name='rwandafdadrug',
            name='brand_name',
            field=models.TextField(help_text='Brand/Trade name of the drug'),
        ),
        migrations.AlterField(
            model_name='rwandafdadrug',
            name='distributor',
            field=models.TextField(help_text='Distributor company'),
        ),
        migrations.AlterField(
            model_name='rwandafdadrug',
            name='dosage_form',
            field=models.TextField(help_text='Dosage form (e.g., Tablet, Capsule, Injection)'),
        ),
        migrations.AlterField(
            model_name='rwandafdadrug',
            name='generic_name',
            field=models.TextField(help_text='Generic name / active ingredient'),
        ),
        migrations.AlterField(
            model_name='rwandafdadrug',
            name='local_agent',
            field=models.TextField(help_text='Local agent in Rwanda'),
        ),
        migrations.AlterField(
            model_name='rwandafdadrug',
            name='manufacturer',
            field=models.TextField(help_text='Drug manufacturer'),
        ),
        migrations.AlterField(
            model_name='rwandafdadrug',
            name='strength',
            field=models.TextField(help_text='Drug strength (e.g., 500mg, 1% w/v)'),
        ),
    ]
