# Generated by Django 4.2.7 on 2026-02-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='population_type',
            field=models.CharField(blank=True, choices=[('young', 'Young (18-35)'), ('pregnant', 'Pregnant'), ('elderly', 'Elderly (65+)'), ('extreme', 'Extreme Age')], help_text='Population type for clinical safety checks', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
