# Generated by Django 6.0.1 on 2026-02-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_population_type_userprofile_height_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age_category',
            field=models.CharField(blank=True, choices=[('young_child', 'Young Child (0-5 years)'), ('older_child', 'Older Child (6-11 years)'), ('adult', 'Adult (12-65 years)'), ('elderly', 'Elderly (65+ years)')], help_text='Patient age category for clinical considerations', max_length=20, null=True),
        ),
    ]
