# Generated by Django 6.0.1 on 2026-02-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_age_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Patient gender', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_pregnant',
            field=models.BooleanField(default=False, help_text='Is the patient pregnant (only applicable for female patients)'),
        ),
    ]
