# Generated by Django 6.0.1 on 2026-02-14 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_gender_userprofile_is_pregnant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, help_text='Patient age in years (exact age for clinical safety checks)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_lactating',
            field=models.BooleanField(default=False, help_text='Is the patient lactating/breastfeeding (only applicable for female patients)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age_category',
            field=models.CharField(blank=True, choices=[('young_child', 'Young Child (0-5 years)'), ('older_child', 'Older Child (6-11 years)'), ('adult', 'Adult (12-65 years)'), ('elderly', 'Elderly (65+ years)')], help_text='Patient age category (auto-calculated from age if not provided)', max_length=20, null=True),
        ),
    ]
