# Generated by Django 6.0.1 on 2026-02-14 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doses', '0001_initial'),
        ('medicines', '0004_drug_patientprofile_contraindication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(help_text='When this medication dose is scheduled')),
                ('local_time', models.DateTimeField(help_text="User's local time for this dose")),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active')),
                ('alarm_sent', models.BooleanField(default=False, help_text='Whether alarm has been sent for this schedule')),
                ('alarm_sent_at', models.DateTimeField(blank=True, help_text='When the alarm was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dose_log', models.OneToOneField(blank=True, help_text='Associated dose log for this schedule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedule', to='doses.doselog')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to='medicines.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medication Schedule',
                'verbose_name_plural': 'Medication Schedules',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='AlarmNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App Alert')], default='in_app', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When notification was delivered', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When user acknowledged the notification', null=True)),
                ('is_successful', models.BooleanField(default=False, help_text='Whether notification was successfully delivered')),
                ('error_message', models.TextField(blank=True, help_text='Any error that occurred during delivery', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_notifications', to=settings.AUTH_USER_MODEL)),
                ('medication_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alarms.medicationschedule')),
            ],
            options={
                'verbose_name': 'Alarm Notification',
                'verbose_name_plural': 'Alarm Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['user', 'scheduled_time', 'is_active'], name='alarms_medi_user_id_632957_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['alarm_sent', 'scheduled_time'], name='alarms_medi_alarm_s_f73c58_idx'),
        ),
    ]
