# Generated by Django 5.2.11 on 2026-02-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationschedule',
            name='acknowledged',
            field=models.BooleanField(default=False, help_text='Whether user has acknowledged the alarm (taken/snooze/dismiss)'),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='alarm_repeat_count',
            field=models.IntegerField(default=0, help_text='Number of times alarm has been repeated (auto-repeat every 10s)'),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='last_alarm_at',
            field=models.DateTimeField(blank=True, help_text='When the last alarm was triggered', null=True),
        ),
    ]
