# Generated by Django 6.0.2 on 2026-02-12 18:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_id', models.CharField(help_text='Format: 00x0y0zph/hp0n (Country-Province-District-Type-Number)', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Pharmacy ID must be in format: 00x0y0zph/hp0n', regex='^\\d{3}\\d{2}\\d{2}(PH|HP)\\d{2}$')])),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('facility_name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('pharmacy', 'Pharmacy'), ('hospital', 'Hospital')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacy Admin',
                'verbose_name_plural': 'Pharmacy Admins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdverseReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('allergic', 'Allergic Reaction'), ('side_effect', 'Side Effect'), ('adverse_event', 'Adverse Event'), ('medication_error', 'Medication Error'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening')], max_length=20)),
                ('medication_name', models.CharField(max_length=200)),
                ('medication_dosage', models.CharField(blank=True, max_length=100)),
                ('medication_batch', models.CharField(blank=True, max_length=50)),
                ('symptoms', models.TextField(help_text='Describe the symptoms experienced')),
                ('onset_time', models.DateTimeField(help_text='When did the reaction start?')),
                ('duration', models.CharField(blank=True, help_text='How long did the reaction last?', max_length=100)),
                ('treatment_given', models.TextField(blank=True, help_text='What treatment was provided?')),
                ('outcome', models.CharField(choices=[('recovered', 'Fully Recovered'), ('recovering', 'Recovering'), ('ongoing', 'Ongoing'), ('permanent', 'Permanent Damage'), ('death', 'Death')], default='recovering', max_length=50)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.CharField(choices=[('patient', 'Patient'), ('pharmacy_admin', 'Pharmacy Admin'), ('healthcare_provider', 'Healthcare Provider'), ('family', 'Family Member')], default='patient', max_length=20)),
                ('requires_follow_up', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_reactions', to=settings.AUTH_USER_MODEL)),
                ('pharmacy_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_reactions', to='saluslogica.pharmacyadmin')),
            ],
            options={
                'verbose_name': 'Adverse Reaction',
                'verbose_name_plural': 'Adverse Reactions',
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientPharmacyAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_associations', to=settings.AUTH_USER_MODEL)),
                ('pharmacy_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_associations', to='saluslogica.pharmacyadmin')),
            ],
            options={
                'verbose_name': 'Patient-Pharmacy Association',
                'verbose_name_plural': 'Patient-Pharmacy Associations',
                'unique_together': {('patient', 'pharmacy_admin')},
            },
        ),
    ]
