# Generated by Django 5.2.11 on 2026-03-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saluslogica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adversereaction',
            name='outcome',
            field=models.CharField(choices=[('recovered', 'Fully Recovered'), ('recovering', 'Recovering'), ('not_recovered', 'Not Recovered'), ('ongoing', 'Ongoing'), ('unknown', 'Unknown'), ('permanent', 'Permanent Damage'), ('death', 'Death')], default='recovering', max_length=50),
        ),
    ]
