# Generated by Django 6.0.1 on 2026-02-11 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('local_time', models.DateTimeField()),
                ('user_timezone', models.CharField(default='UTC', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('missed', 'Missed'), ('snoozed', 'Snoozed')], default='pending', max_length=10)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('snooze_count', models.IntegerField(default=0)),
                ('trigger_minute', models.CharField(blank=True, max_length=10, null=True)),
                ('alarm_group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='medicines.medicine')),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='DoseReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('notification', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS'), ('alarm', 'Alarm')], max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dose_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='doses.doselog')),
            ],
        ),
        migrations.CreateModel(
            name='DoseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doses_scheduled', models.IntegerField(default=0)),
                ('doses_taken', models.IntegerField(default=0)),
                ('doses_missed', models.IntegerField(default=0)),
                ('doses_snoozed', models.IntegerField(default=0)),
                ('adherence_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='medicines.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'medicine', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='doselog',
            index=models.Index(fields=['medicine', 'status', 'scheduled_time'], name='doses_dosel_medicin_d48746_idx'),
        ),
        migrations.AddIndex(
            model_name='doselog',
            index=models.Index(fields=['status', 'scheduled_time'], name='doses_dosel_status_cc08c7_idx'),
        ),
    ]
